# Generated by Django 5.2.4 on 2025-07-14 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_candidato_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.empresa'),
        ),
    ]
